# Generated by Django 2.2.5 on 2019-11-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
