# Generated by Django 2.2.5 on 2019-11-02 14:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_auto_20191102_2210'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserExtra',
            new_name='Profile',
        ),
    ]
