# Generated by Django 2.2.5 on 2019-11-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191104_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatar/%y%m%d/'),
        ),
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
