# Generated by Django 2.2.5 on 2019-11-26 03:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20191106_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='register_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
