# Generated by Django 2.2.5 on 2019-11-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_register_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-register_date',)},
        ),
        migrations.AddField(
            model_name='user',
            name='article_posted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='comment_reply',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='follower',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.IntegerField(default=0),
        ),
    ]
