# Generated by Django 2.2.5 on 2019-11-17 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20191106_2240'),
        ('comment', '0003_remove_comment_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='user.User'),
        ),
    ]
